### ISSUE TITLE
Performance and accessibility of the website

### ISSUE THREAD

**Issue by agpt8** [zero-to-mastery/zero-to-mastery-website#171]
Upon auditing the website with lighthouse (auditing tool in chrome dev tools), I found that the load time can be improved a lot. There are a lot of static elements present on the main page that can be cached to improve load times and accessibility can be improved.

There are vulnerabilities present in the dependencies and many of the assets are served using HTTP/1.1 instead of using HTTP/2

Note: Audit was done in Desktop and Mobile mode with no throttling. Mobile mode performance is worse than Desktop mode.

Mobile Mode:
![image](https://user-images.githubusercontent.com/16762897/61522993-1e4d1b80-aa31-11e9-93cf-5774d3810e33.png)

Desktop Mode:
![image](https://user-images.githubusercontent.com/16762897/61523085-463c7f00-aa31-11e9-8429-ff06e1808a85.png)

**Comment by Dhaval1403** [comment]
The PR for this issue has been merged :)
