### ISSUE TITLE
Add GeeksforGeeks under general resources on the website

### ISSUE THREAD

**Issue by agpt8** [zero-to-mastery/zero-to-mastery-website#172]
Add link to geeksforgeeks portal under general resources on the website

**Comment by arjunkharbanda** [comment]
You can submit PR and I will merge it right away.

**Comment by StrykerKent** [comment]
Just a heads up... this has been completed.

**Comment by arjunkharbanda** [comment]
@MattCSmith @Dhaval1403 can you close this issue
