### ISSUE TITLE
<script> in the middle of the code

### ISSUE THREAD

**Issue by balabis** [zero-to-mastery/zero-to-mastery-website#34]
Hey, shouldn't the "<script src="assets/js/script.js"></script>" be in the bottom of the <body>?
It's now somewhere in the middle of the code and I've been wondering why it's sitting there :)

**Comment by Polcat000** [comment]
@balabis In which file? I was trying to find it to patch that, but I can't find it.

**Comment by IronCoderXYZ** [comment]
Fixed in PR40: https://github.com/zero-to-mastery/zero-to-mastery-website/pull/40

The script file is responsible for displaying and starting the about video, the author likely put it there because it relates to the video section.
